/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9071f7e8-6057-4d18-a76b-b93206236cfb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_UMZtsYe89",
    "aws_user_pools_web_client_id": "53h1qet203eqmq15443gp66cq6",
    "oauth": {}
};


export default awsmobile;
